#!/bin/bash

post_data()
{
cat <<EOF
{
  "time": "$(date +%Y-%d-%mT%H:%M:%S.000000%z)",
  "name": "$radarr_movie_title",
  "eventtype": "$radarr_eventtype"
}
EOF
}

curl -X POST -H "Content-Type: application/json" -H 'Authorization: Bearer '$HA_TOKEN \
--data "$(post_data)" \
http://hbox:8123/api/events/update_video_db
